spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl

  redis:
    #    host: localhost
    host: 127.0.0.1
    port: 6379

logging:
  file:
    path: ./log